Error: The element has no supported sources. Can u fix above? If sound file is a problem...remoev it..we ll see later
Another is ...can you show Ones in the group of 3...this way kids can learn a way of associating ...
If I need to show lets say 5A...I ll show something like below...
A  A  A
A  A